### ISSUE TITLE
[ENHANCEMENT REQUEST] - Multiple server connections

### ISSUE THREAD

**Issue by OvileAmriam** [ov-studio/vNetworkify#12]
- CLIENT:
  - Allow multiple connections to different machines on different ports.

- SERVER:
  - Allow multiple http servers on different ports.

**Comment by Aviril** [comment]
> * CLIENT:
>   
>   * Allow multiple connections to different machines on different ports.
> * SERVER:
>   
>   * Allow multiple http servers on different ports.

Merged: https://github.com/ov-studio/vNetworkify/releases/tag/v.3.0.0
