### ISSUE TITLE
[ENHANCEMENT REQUEST] - Instance Tracker

### ISSUE THREAD

**Issue by Anisa-Nur** [ov-studio/vNetworkify#16]
Destroy socket's (room, network...etc) instances similarly as `client` manager: https://github.com/ov-studio/vNetworkify/blob/main/src/managers/socket/index.js#L112

How should it be?
https://github.com/ov-studio/vNetworkify/blob/main/src/managers/socket/client.js#L29

**Comment by Aviril** [comment]
> Destroy socket's (room, network...etc) instances similarly as `client` manager: https://github.com/ov-studio/vNetworkify/blob/main/src/managers/socket/index.js#L112
> 
> How should it be? https://github.com/ov-studio/vNetworkify/blob/main/src/managers/socket/client.js#L29

Merged: https://github.com/ov-studio/vNetworkify/releases/tag/v.3.0.0
