### ISSUE TITLE
[FEATURE REQUEST] - HTTPS + SSL-Cert support

### ISSUE THREAD

**Issue by OvileAmriam** [ov-studio/vNetworkify#17]
- Add support to automatically read `sslcert.env` during startup incase of existence.
- Based on availability of SSL cert prefer `https` connection over `http`.
- Apply same methodology over websocket protocols as well prefer `wss` over `ws`.
- Incase if `ws` is used encode all socket messages (`tea` encode, perhaps??); Key should be sent to client only once during the initialization of connection as suggested by @Anisa-Nur.

**Comment by Aviril** [comment]
Implemented SSL + HTTPS support. Kindly refer: https://github.com/ov-studio/vNetworkify/releases/tag/v.3.2.0
Do note, implemented [vNetworkify.setSSLCert](https://github.com/ov-studio/vNetworkify/wiki/Glossary:-Server#-vnetworkifysetsslcert-server) method instead to suit for better personal strategies.

**Comment by Aviril** [comment]
> Apply same methodology over websocket protocols as well prefer wss over ws.

This concept is purely client side which already works as expected. Dynamically allocates websocket encrypted/unencrypted protocol based on `isSSL` connection property on client side

**Comment by Anisa-Nur** [comment]
> Incase if ws is used encode all socket messages (tea encode, perhaps??); Key should be sent to client only once during the initialization of connection as suggested by @Anisa-Nur.

From current POV, it doesn't seems worth to implement anyway due to causing performance slower + key being sent over http protocol. Rather switch to `https` for such concerns.
