### ISSUE TITLE
[FEATURE REQUEST] SOCKET - Utility Functions

### ISSUE THREAD

**Issue by go4cas** [ov-studio/vNetworkify#3]
The following utility functions would be great to build a management tool for the socket server:

- `vNetworkify.fetchSockets()`: Retrieve an array of the sockets
- `socket.fetchNetworks()`: Retrieve an array of the networks for the provided socket instance
- `socket.fetchRooms()`: Retrieve an array of the rooms for the provided socket instance
- `socket.fetchClients()`: Retrieve an array of the clients connected to the provided socket instance
- `socket.fetchClients()`: Retrieve an array of the clients connected to the provided room instance

**Comment by OvileAmriam** [comment]
> The following utility functions would be great to build a management tool for the socket server:
> 
> * `vNetworkify.fetchSockets()`: Retrieve an array of the sockets
> * `socket.fetchNetworks()`: Retrieve an array of the networks for the provided socket instance
> * `socket.fetchRooms()`: Retrieve an array of the rooms for the provided socket instance
> * `socket.fetchClients()`: Retrieve an array of the clients connected to the provided socket instance
> * `socket.fetchClients()`: Retrieve an array of the clients connected to the provided room instance

Merged w/ release: https://github.com/ov-studio/vNetworkify/releases/tag/v.2.2.4
