### ISSUE TITLE
[FEATURE REQUEST] SOCKET - Connection Error Events

### ISSUE THREAD

**Issue by go4cas** [ov-studio/vNetworkify#5]
Include events to trap connection errors for sockets on both server and client. It would be great if this could include a `reason` (similar to socket.io) to allow for different strategies (throw exception, manual reconnection, etc), based on the reason for disconnection.

**Comment by OvileAmriam** [comment]
Implemented & Merged w/ release: https://github.com/ov-studio/vNetworkify/releases/tag/v.2.3.0
