### ISSUE TITLE
[ENHANCEMENT REQUEST] SOCKET - Supply Timestamp on `socket.onServerDisconnect`

### ISSUE THREAD

**Issue by OvileAmriam** [ov-studio/vNetworkify#9]
Supply a parameter to know since how long the server been running, this could be either tick or `date` object itself as such indicated below:
```js
socket.onServerDisconnect(function(startedOn, endedOn, estimatedRunTicks) {

})
```

**Comment by Aviril** [comment]
> Supply a parameter to know since how long the server been running, this could be either tick or `date` object itself as such indicated below:
> 
> ```js
> socket.onServerDisconnect(function(startedOn, endedOn, estimatedRunTicks) {
> 
> })
> ```

Merged: https://github.com/ov-studio/vNetworkify/releases/tag/v.2.4.1
